# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test',
                'doc_host': 'https://abalone1.github.io',
                'git_url': 'https://github.com/abalone1/test',
                'lib_path': 'test'},
  'syms': {'test.core': {'test.core.foo': ('core.html#foo', 'test/core.py')}}}
